### PR TITLE
Fix child-frame disappearing on macOS by making frame visible before setting its position

### PR DESCRIPTION
**Pull request by jiegec**
Oh man it realllllly works!!!!
Thanks for https://emacs-china.org/t/topic/4662/18

### CODE REVIEW

**Comment by jiegec** [comment]
emmmm 下面有一部分是emacs自动indent的时候改的空格。。这部分我可以去掉

**Comment by jiegec** [comment]
等会，我怎么又调出了BUG？？？？懵逼

**Comment by tumashu** [comment]
你缩进有问题，不要用tab，用空格缩进

**Comment by jiegec** [comment]
已更新

**Comment by tumashu** [comment]
ok, thanks

**Pull request merged**
