### PR TITLE
Fix defcustom type definitions

### PR DESCRIPTION
**Pull request by RuijieYu**
So that certain `setopt` [1] actions do not issue warnings.  In addition, fixed minor issues around defcustom when I see them, like their docstrings and initial values.

[1] `setopt` is available since Emacs 29.

* pyim-scheme.el {widget} pyim-scheme: added a type alias of a "scheme" for later reuse pyim-default-scheme: switch to use more concrete type 'pyim-scheme

* pyim-cregexp.el pyim-cregexp-fallback-scheme: use type 'pyim-scheme.

* pyim-dcache.el pyim-dcache-backend: use radio to choose between the two available options.

* pyim-dict.el pyim-dicts: use a more concrete type definition with tags.

* pyim-indicator.el pyim-indicator-list: reformatted default value; removed overlapping type nil from (repeat function), becuase `(repeat ...)` allows empty lists. pyim-indicator-use-post-command-hook: quote `post-command-hook` in docstring.

* pyim-outcome.el pyim-outcome-magic-converter: added nil type, because it can be nil. pyim-outcome-trigger-function: prefer function quote in its init value.

* pyim-page.el:
{widget} pyim-page-tooltip-1: added a type alias for a single tooltip.
{widget} pyim-page-tooltip: added a type alias for "one or more" tooltips.
{widget} pyim-page-style: added a type alias for a page style.
pyim-page-tooltip: "Emacs" shoule be upper case; use type alias as its type.
pyim-page-tooltip-style-alist: use type aliases to narrow down type def.

* pyim-pinyin.el pyim-pinyin-fuzzy-alist: narrow down possible type def. pyim-pinyin--shengmu: renamed from `pyim-pinyin--shenmu`.

* pyim-process.el pyim-english-input-switch-functions: type should be a list of functions. pyim-force-input-chinese-functions: type should be a list of functions. pyim-process-autoselector: changed docstring to specify it is a "list"; removed overlapping type nil.
pyim-process-run-delay: type should be number because of the initial value.

* pyim-punctuation.el pyim-punctuation-dict: reworked type def for better customize view. pyim-punctuation-half-width-functions: removed overlapping type nil.

### CODE REVIEW

**Comment by tumashu** [comment]
Wow, this is a big change, do you have signed gpl paper?

**Comment by RuijieYu** [comment]
No.  Please guide me through how to do it, or point at a URL where I can get started, thanks.

**Comment by RuijieYu** [comment]
If you mean the FSF copyright paper for Emacs, then yes, I do.  Otherwise, please let me know what it is, since I can't find much information within the repository.  Thanks.

**Comment by tumashu** [comment]
```
the FSF copyright paper for Emacs
```
Yes, for pyim is a Gnu-Elpa package.

**Comment by tumashu** [comment]
Merged, thanks!

**Pull request merged**
