### PR TITLE
(+ sanma (triple) Zhengma)

### PR DESCRIPTION
**Pull request by p1uxtar**
Add sanma zhengma scheme.

The [pyim-smzmdict](https://github.com/p1uxtar/pyim-smzmdict) has been merged by melpa (PR [#7456](https://github.com/melpa/melpa/pull/7456)).

Following the comments when PR reviewed, I have added some configuration of pyim in the code, and I will further correct if there are some incompatibilities.

I can't append a comment for the previous PR #388 , so I create a new one and then will close it.

By the way, I'm erStern who changed ID, the maintainer of [pyim-cangjie5dict](https://github.com/p1uxtar/pyim-cangjie5dict). I also changed the URL of cangjie5dict.

### CODE REVIEW

**Comment by tumashu** [comment]
你 gpl 纸质协议签署过吗？ 现在 pyim 是 gnu elpa 包，需要这些操作。

**Comment by tumashu** [comment]
另外，可以尝试将词库放到 gnu elpa

**Comment by p1uxtar** [comment]
没签过，从哪儿可以找到指南或教程么？

**Comment by tumashu** [comment]
我觉得一个更省事的方式是，将这些代码直接写到 pyim-smzmdict.el 里面，我在 pyim 里面给你写一句介绍。

**Comment by tumashu** [comment]
这样就省得你弄 gpl 协议了。

**Comment by p1uxtar** [comment]
现在这版就有，require之后，`(pyim-smzmdict-enable)`就能运行。

我本来没写pyim的配置，melpa就一直不给过 😂

**Comment by tumashu** [comment]
```
(setq default-input-method "pyim"
      pyim-default-scheme 'smzm
      pyim-enable-shortcode nil
      pyim-punctuation-translate-p '(auto yes no)
      pyim-page-tooltip 'popup)
```
这段不应该出现在  pyim-smzmdict.el，应该在 pyim-smzmdict.el 的 README 中

**Comment by tumashu** [comment]
https://github.com/tumashu/pyim/commit/a55bfa5f883db9c10847ce645575d0253a7b5654

**Pull request closed without merging**
