### PR TITLE
simplify pyim-entered-next-imelem-position to make it work with wubi

### PR DESCRIPTION
**Pull request by levindu**
This is IMO a more robust way to get the next imelem position which
is workable both in pinyin and wubi.

The end-position is determinted by the length of the imobj created
from [(point-min)..pos) of the pyim-entered-buffer, which meets the
following condition:

    forward:
        should meet (orig-imobj-len + num) > new-imobj-len

    backward:
        if (orig-imobj-len > num)
            should meet (orig-imobj-len - num) == new-imobj-len
        else
            end-position=(point-min)

### CODE REVIEW

**Comment by tumashu** [comment]
merged, thanks

**Comment by tumashu** [comment]
pyim用五笔的贡献者不多，如果需要合作者权限，就说一声

**Comment by levindu** [comment]
> pyim用五笔的贡献者不多，如果需要合作者权限，就说一声

好的，现在的 PR 方式还好，我的提交暂时也不多，只是改一下代码让五笔输入
更舒服一些。有需要的话会跟你联系🤝

**Comment by tumashu** [comment]
ok

**Pull request merged**
