### PR TITLE
修复pyim-enter选词

### PR DESCRIPTION
**Pull request by QiangF**

### CODE REVIEW

**Comment by QiangF** [comment]
就是 https://github.com/tumashu/pyim/pull/302，当时直接在github里改的，添加了很多不应该的东西，这个如果别的输入法不用编辑输入框，对它们一点影响都没有。

**Comment by tumashu** [comment]
merged, thanks!

**Comment by tumashu** [comment]
@QiangF 我稍微做了一些调整，比较方便调试， 逻辑基本没变， 你可以测试一下 https://github.com/tumashu/pyim/commit/7df2ef4d0ef0b26dc4e4175031e328aa9d959a43

**Comment by tumashu** [comment]
@QiangF 我再次做了调整，这次使用 pyim-outcome-history 来管理 pyim 的outcome，相对来说更加简单，好理解，具体细节可以看 pyim-outcome-history 的 docstring

**Comment by tumashu** [comment]
https://github.com/tumashu/pyim/commit/eadb41ca0557538666b344a11ca9051b9b6a83f6

**Comment by tumashu** [comment]
另外，编辑 entered 的命令，我添加了 imelem 的概念， 用 imobj 是不对的，具体细节 查看 pyim-imobjs 的 docstring

**Comment by QiangF** [comment]
1. 输入ni
2. pyim-entered-delete-backward-imelem
3. overlay 你 ，没有删除
发现是这个判断放的位置要改一下：

    (when (> (length (pyim-entered-get)) 0)

这是改过的：

    (defun pyim-entered-refresh-1 ()
    "查询 `pyim-entered-buffer' 光标前的拼音字符串（如果光标在行首则为光标后的）, 显示备选词等待用户选择。"
    (let* ((scheme-name (pyim-scheme-name))
            pinyin-to-translate)
        (pyim-with-entered-buffer
        (setq pinyin-to-translate
                (if (equal 1 (point))
                    (buffer-string)
                (buffer-substring-no-properties 1 (point)))))
        (setq pyim-imobjs (pyim-imobjs-create pinyin-to-translate scheme-name))
        (setq pyim-candidates
            (or (delete-dups (pyim-candidates-create pyim-imobjs scheme-name))
                (list pinyin-to-translate)))
        (setq pyim-candidate-position 1)
        (pyim-preview-refresh)
        (when (> (length (pyim-entered-get)) 0)
        (pyim-page-refresh))))

    (defun pyim-entered-refresh (&optional no-delay)
    "延迟 `pyim-exhibit-delay-ms' 显示备选词等待用户选择。"
        (when pyim--exhibit-timer (cancel-timer pyim--exhibit-timer))
        (cond
        ((or no-delay (not pyim-exhibit-delay-ms) (eq pyim-exhibit-delay-ms 0))
        (pyim-entered-refresh-1))
        (t
        (setq pyim--exhibit-timer
                (run-with-timer (/ pyim-exhibit-delay-ms 1000.0)
                                nil
                                #'pyim-entered-refresh-1)))))

**Comment by tumashu** [comment]
Fixed!

**Pull request merged**
